version: "3"

services:
  db:
    container_name: odas-db
    image: postgres
    environment:
      - POSTGRES_USER=odas
      - POSTGRES_PASSWORD=odas
  backend:
    container_name: odas-backend
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    container_name: odas-frontend
    depends_on:
      - backend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
