version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=odsi
      - POSTGRES_PASSWORD=odsi
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"